name: Documentation CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "fix/**"
      - "hotfix/**"

  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read

jobs:
  validate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material

      - name: Build Documentation
        run: |
          mkdocs build --strict
